<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Commune;
use App\Models\Wilaya;

class CommuneSeeder extends Seeder
{
    public function run(): void
    {
        $communes = [
            'Adrar' => ['Adrar','Tamest','Charouine','Reggane','In Zghmir','Tit','Ksar Kaddour','Tsabit','Timimoun','Ouled Said','Zaouiet Kounta','Aoulef','Timokten','Tamentit','Fenoughil','Tinerkouk','Deldoul','Sali','Akabli','Metarfa','Ouled Ahmed Timmi','Bordj Badji Mokhtar','In Salah','In Guezzam'],
            'Chlef' => ['Chlef','Ténès','Benairia','El Karimia','Tadjna','Taougrite','Beni Haoua','Sobha','Harchoun','Ouled Fares','Sidi Akkacha','Boukadir','Beni Rached','Talassa','Herenfa','Oued Goussine','Djendel','El Marsa','Chettia','Sidi Abderrahmane','Moussadek','El Hadjadj','Labiod Medjadja','Oued Sly','Abou El Hassan','Sendjas','Zeboudja','Breira','Beni Bouattab','El Fodda','Ouled Ben Abdelkader','Oum Drou'],
            'Laghouat' => ['Laghouat','Ksar El Hirane','Bennasser Ben Chohra','Sidi Makhlouf','Hassi Delaa','Hassi R\'Mel','Ain Mahdi','Tadjemout','Kheneg','Gueltat Sidi Saad','Ain Sidi Ali','Beidha','Brida','El Ghicha','Hadj Mechri','Sebgag','Taouiala','Tadjrouna','Aflou','El Assafia','Oued Morra','Oued M\'zi'],
            'Oum El Bouaghi' => ['Oum El Bouaghi','Ain Beida','Ain M\'lila','El Amiria','Souk Naamane','Ain Fakroun','Rahia','Ksar Sbahi','Oued Nini','Behir Chergui','El Djazia','Ain Zitoun','Ouled Hamla','Bir Chouhada','Ain Diss','Fkirina','Souk El Naâm','El Fedjoudj','Ain Babouche','Beriche','Hanchir Toumghani','El Harmilia'],
            'Batna' => ['Batna','Ghassira','Maafa','Merouana','Seriana','Ouldje','Bitam','Metkaouak','Ouled Si Slimane','Fesdis','El Madher','Tazoult','N\'gaous','Guigba','Inoughissen','Ouyoun El Assafir','Djerma','Tilatou','Ain Touta','Boulhilet','Djezzar','Gosbat','Ouled Aouf','Hidoussa','Menaa','El Hassi','Oued El Ma','Lazrou','Tkout','Ain Djasser','Ouled Zouai','Beni Foudhala El Hakania','N\'gaous','Ras El Aioun','Chir','Ouled Ammar','El Korichi','Boumagueur','Barika','Djaber','Sefiane','El Anseur','Ain Yagout','Faour','Ichmoul','Ghassira','Arris','Kimmel','Tigherghar','Boulhilet','Lemsane','Oued Chaaba','Taxlent','Gosbat','Ain Touta'],
            'Béjaïa' => ['Béjaïa','Amizour','Ferraouen','Oued Ghir','Boudjellil','El Kseur','Mallou','Akbou','Ighram','Amalou','Ighil Ali','Feraoun','Tizi N\'Berber','Chellata','Tamokra','Timezrit','Souk El Tenine','Melbou','Aokas','Beni Maouche','Darguina','Sidi Ayad','Aokas','Beni Ksila','Kendira','Tifra','Adekar','Akfadou','Leflaye','Kherrata','Draa El Kaid','Tamridjet','Ait Smail','Boukhlifa','Taourirt Ighil','Chemini','Souk Oufella','Tazmalt','Ait R\'Zine','El Flaye','Beni Djellil','Iffri','Ouzellaguen','Beni Mellikeche','Seddouk','Taskriout','Tibane','Tala Hamza','Barbacha','Beni Zmenzer','Imsouhal','Tinebdar','Tichy','Oued Marsa'],
            'Biskra' => ['Biskra','Oumache','Branis','El Hadjeb','Ain Zaatout','Chetma','Sidi Okba','Ain Naga','El Haouch','Zeribet El Oued','Ain Ben Noui','Djemorah','El Kantara','Tolga','Bouchagroune','Foughala','El Ghrous','Lichana','Ourlal','Mlili','Doucen','El Feidh','Biskra','Lioua','Sidi Khaled','Ras El Miad','El Abiodh Sidi Cheikh','El Hichria','Ouled Djellal'],
            'Béchar' => ['Béchar','Erg Ferradj','Meridja','Igli','Beni Ounif','Boukais','Mogheul','Timoudi','Lahmar','Tabelbala','Taghit','Ksabi','Ouled Khoudir','Abadla'],
            'Blida' => ['Blida','Chebli','Larbaa','Meftah','Hammam Melouane','El Affroun','Chiffa','Bouarfa','Oued Djer','Beni Tamou','Bougara','Soumaa','Beni Mered','Boufarik','El Afroun','Oued El Alleug','Ain Romana','Bouinan','Ben Khellil','Souhane','Ouled Selama','Djebabra'],
            'Bouira' => ['Bouira','El Asnam','Sour El Ghozlane','Bir Ghbalou','Haizer','Bechloul','Bordj Okhriss','Ain El Hadjar','Dirrah','El Hachimia','Raouraoua','Chorfa','Ain Lahdjar','Taghzout','Ridane','Maâla','Ahnif','Mâatkas','Lakhdaria','Bouderbala','Dirah','Ain Turk','El Adjiba','El Mokrani','Saharidj','Mezdour','Ait Laaziz','Kadiria','Zbarbar','Djebahia','Ain El Turc','Ait Mansour','M\'Chedallah','Souk El Khemis','Ouled Rached'],
            'Tamanrasset' => ['Tamanrasset','Abalessa','In Ghar','In Guezzam','Foggaret Ezzaouia','Tazrouk','Tin Zaouatine','Idles'],
            'Tébessa' => ['Tébessa','Morkhane','Bir El Ater','Cheria','Stah Guentis','El Aouinet','Lahouidjbet','Safsaf El Ouesra','Hammamet','Ouenza','El Ogla','Morsott','El Meridj','Bir Mokkadem','Ain Zerga','El Houidjbet','Ferkane','Bekkaria','Boukhadra','Oum Ali','Youkous','El Kouif','Thlidjene','Ain El Assel'],
            'Tlemcen' => ['Tlemcen','Beni Mester','Ain Tallout','Remchi','El Fehoul','Ghazaouet','Souahlia','Msirda Fouaga','Ain Fezza','Ouled Riyah','Bab El Assa','Dar Yaghmouracen','Fellaoucene','Amieur','Ain Youcef','Hammam Boughrara','Sebaa Chioukh','Terni Beni Hdiel','Bensekrane','Ain Nehala','Henaya','Maghnia','Hammam Boughrara','Sidi Abdelli','Azails','El Gor','Nedroma','Honaïne','Tlemcen','Beni Snous','Beni Boussaid','Marsa Ben M\'hidi','Oued Chouly','Ain Ghoraba','Chetouane','Mansourah','Beni Ouarsous','Souahlia','Sidi Medjahed','Bouhlou'],
            'Tiaret' => ['Tiaret','Mechraa Safa','Ain Bouchekif','Sidi Ali Mellal','Ain Zarit','Bougara','Medrissa','Ain Deheb','Naima','Mahia','Sougueur','Sidi Abderrahmane','Oued Lilli','Medroussa','Ain Kermes','Ksar Chellala','Guertoufa','Sidi Bakhti','Rechaiga','Nadorah','Dahmouni','Aïn Bouchekif','Frenda','Ain El Hadid','Tousnina','Hamadia','Madna','Tagdempt','Zmalet El Emir Abdelkader','Si Abdelghani','Ain El Hadid'],
            'Tizi Ouzou' => ['Tizi Ouzou','Ain El Hammam','Akbil','Freha','Souama','Mechtrass','Ait Agouaou','Ouaguenoun','Ain Zaouia','Mizrana','Iloula Oumalou','Yahia Moussa','Beni Zmenzer','Ifigha','Ait Chafaa','Draâ Ben Khedda','Tizi Rached','Beni Aissi','Beni Douala','Beni Mahmoud','Beni Ziki','Tizi Gheniff','Boghni','Assi Youcef','Abi Youcef','Ain El Hammam','Akbil','Akerrou','Makouda','Sidi Namane','Timizart','Ouacif','Ait Yahia','Ait Mahmoud','Mekla','Tizi Ouzou','Draa El Mizan','Tizi Nthleta','Ait Bouaddou','Bounouh','Ait Aggouaou','Idjeur','Imsouhel','Imsouhal','Frikat','Bouzeguene','Illoula Oumalou','Ait Boumahdi','Larbaâ Nath Irathen','Tizi Rached','Irdjen','Timizart','Ouaguenoun','Tigzirt','Dellys','Azzefoun','Iflissen','Beni Zemenzer'],
            'Alger' => ['Alger Centre','Sidi M\'hamed','El Madania','Belouizdad','Bab El Oued','Bologhine','Casbah','Oued Koriche','Bir Mourad Raïs','El Biar','Bouzareah','Birkhadem','El Harrach','Baraki','Oued Smar','Bachdjerrah','Hussein Dey','Kouba','Bourouba','Dar El Beida','Bab Ezzouar','Ben Aknoun','Dely Ibrahim','Hammamet','Raïs Hamidou','Djasr Kasentina','El Mouradia','Hydra','Mohammadia','Bordj El Bahri','El Magharia','Ain Taya','Bordj El Kiffan','El Marsa','Ain Benian','Staoueli','Zeralda','Mahelma','Rahmania','Souidania','Cheraga','Ouled Fayet','El Achour','Draria','Douéra','Baba Hassen','Khraicia','Saoula'],
            'Djelfa' => ['Djelfa','Moudjbar','El Idrissia','Birine','Ain Maabed','Sed Rahal','Faidh El Botma','Douis','Hassi Bahbah','Ain Chouhada','Guernini','Selmana','Ain El Ibel','Charef','Zaccar','El Khemis','Dar Chioukh','Charef','Messaad','Guettara','Sidi Baizid','Mliliha','El Azizia','Had-Sahary','Sougueur','Ain Fekka','Tadmit'],
            'Jijel' => ['Jijel','El Aouana','Ziama Mansouriah','El Milia','Texenna','Djimla','Selma Ben Ziada','Kaous','Settara','El Ancer','Sidi Maarouf','Taher','Ouled Yahia Khedrouche','Boudriaa Ben Yadjis','Bordj T\'har','Chekfa','Chahna','El Kennar Nouchfi','Ouadjana','Emir Abdelkader','Ghebala','Bouraoui Belhadef','Djemaa Beni Habibi','Beni Yahia Timizar','El Aioune'],
            'Sétif' => ['Sétif','Ain El Kebira','Ain Arnat','Guenzet','Ain Azel','Djemila','Bougaa','Maoklane','Bir El Arch','Bouandas','Salah Bey','Guidjel','El Ouricia','Beni Aziz','Taya','Ain Legraj','Oued El Bared','Ras El Ma','Beni Fouda','Talaifacene','Guellal','Ain Oulmene','El Eulma','Hamma','Dehamcha','Bir Haddada','Bousselam','Draa Kebila','Mezloug','Belaa','Ain Lahdjar','Hammam Guergour','Hammam Sokhna','Ain Abassa','Serdj El Ghoul','Tachouda','Bazer Sakhra','Beni Mouhli','Ain Roua','Guendouz','Ain Sebt','El Ouldja','Beni Ourtilane','Ain El Hadjel','Ksar El Abtal','Maaouia','Ouled Addouane','Ouled Sabor','Tizi N\'Bechar','Ouled Tebben','Amoucha'],
            'Saïda' => ['Saïda','Doui Thabet','Ain El Hadjar','Ouled Khaled','Moulay Larbi','Youb','Tircine','Sidi Boubekeur','El Hassasna','Sidi Ahmed','Ain Sekhouna','El Breidj','Hounet','Sidi Amar'],
            'Skikda' => ['Skikda','Ben Azzouz','El Hadaiek','Ramdane Djamel','Hamadi Krouma','Oum Toub','Tingaiou','El Harrouch','Zerdazas','Beni Bechir','Emdjez Edchich','Ain Bouziane','Ain Cherchar','Kerkera','Collo','Tamalous','Beni Zid','El Mharzen','Bein El Ouiden','Salah Bouchaour','Oued Zighem','Beni Oulfene','Beni Oulbane','Ouled Attia','Cheraia','Ouled Attia','Fil Fila','Azzaba','Bekkouche Lakhdar','Djendel Saadi Mohamed','Aïn Kechra','Oued El Kébir','Sidi Mezghiche'],
            'Sidi Bel Abbès' => ['Sidi Bel Abbès','Tessala','Ain El Berd','Sidi Khaled','Tenira','Hassi Zehana','Ben Badis','El Hachem','Rouiha','Tilmouni','Mostefa Ben Brahim','Sehala Thaoura','Ain Thrid','Boudjebha El Bordj','Ras El Ma','El Bezoul','Merine','Tabia','Ain Kada','Boukhanafis','Sidi Brahim','Sidi Hamadouche','Marhoum','Ain Tindamine','Mezaourou','Belarbi','Sidi Ali Benyoub','Sidi Ali Boussidi','Oued Sebaa','Badredine El Mokrani','Ben Achour','Bir El Hammam','Lamtar','Sidi Yacoub','Redjem Demouche','Sfissef','Telagh'],
            'Annaba' => ['Annaba','El Hadjar','Berrahal','El Eulma','El Bouni','Oued El Aneb','Cheurfa','Seraidi','Ain Berda','Chetaïbi','Sidi Amar','Treat'],
            'Guelma' => ['Guelma','Nechmaya','Ain Makhlouf','Oued Zenati','Tamlouka','Ain Ben Beida','Bou Hamdane','Ras El Agba','Nador','Bled Amar','Guelaat Bou Sbaa','Ain Larbi','Medjez Sfa','Bouchegouf','Houari Boumediene','Hammam Debagh','Hammam N\'bails','Djeballah Khemissi','El Fedjoudj','Ain Sandel','Héliopolis','Bordj Sabat','Bordj Menaiel','Ain Ben Beida','Ain Hessania'],
            'Constantine' => ['Constantine','Hamma Bouziane','Ibn Ziad','Zighoud Youcef','El Khroub','Ain Abid','Beni Hamidane','Mesaoud Boudjriou','Ouled Rahmoune'],
            'Médéa' => ['Médéa','Ain Boucif','El Azizia','Oum El Djalil','El Omaria','Ouled Hellal','Tizi Mahdi','El Hamdania','Tablat','Sidi Zahar','Ain El Hadjel','Sidi Damed','Kef Lakhdar','Zoubiria','Meftaha','Berrouaghia','Ouled Antar','El Aissaouia','Rebaia','Hannacha','Seghouane','Boghar','Ksar El Boukhari','Saneg','Ain El Hadjel','El Omaria','Benchicao','Ain Ouksir','Derrag','El Hamdania','Ouamri','Si Mahdjoub','Mihoub','Bouchrahil','Ouled Brahim','Soumaa','Aziz','Bouaichoune','El Ktaria','Baata'],
            'Mostaganem' => ['Mostaganem','Stidia','Ain Nouissy','Mazagran','Hassi Mameche','Ain Tedles','Souaflia','Sirat','Bouguirat','Sidi Ali','Mesra','Achaacha','Hadjaj','Ain Boudinar','Sidi Lakhdar','Ouled Maalah','Khadra','El Hassiane','Benabdelmalek Ramdane','Fornaka','Nekmaria','Oued El Kheir','Touahria'],
            "M'Sila" => ["M'Sila",'Belaïba','Maadid','Hammam Dalaa','Sidi Aissa','Ain El Melh','Magra','Bousaada','Ouled Derradj','Ain El Hadjel','Maarif','Berhoum','Ouled Sidi Brahim','Boussaâda','Dehahna','Sidi Ameur','El Houamed','Ouled Slimane','Sidi M\'Hamed','Ben Srour','El Hamel','Souamaa','Ain Fares','Ain Khadra','Soumâa','Beni Ilmane','Ouanougha','Oued Char','Khoubana','Chellal','Ben Zouh','Ouled Madhi','El Brissa'],
            'Mascara' => ['Mascara','Tizi','Ain Fares','Maoussa','El Keurt','Oued El Abtal','Ghriss','Nesmoth','El Gaada','Bou Hanifia','Oued Taria','Ain Fekan','Matemore','El Hachem','El Bordj','Froha','Zahana','Beniane','Sidi Abdeldjebar','Khalouia','El Menaouer','Ain Fekan','Oggaz','Sedjerara','El Ghomri','Ras Ein Amirouche','Hacine','Guerdjoum','Ain Fares','Makdha','Ain Fares'],
            'Ouargla' => ['Ouargla','N\'Goussa','Sidi Khouiled','Hassi Messaoud','Rouissat','El Alia','Tebesbest','Nezla','Touggourt','Temacine','El Hadjira','Taibet','Balidat Ameur','Ain Beida','Megarine','El Borma','Benaceur','Zaouia El Abidia'],
            'Oran' => ['Oran','Gdyel','Bir El Djir','Hassi Bounif','Arzew','Bethioua','Marsat El Hadjadj','Ain El Turk','El Ancar','Es Senia','Misserghine','Boutlelis','Ain El Kerma','El Braya','Hassi Ben Okba','Ben Freha','Hassi Mefsoukh','Sidi Chahmi','El Hassi'],
            'El Bayadh' => ['El Bayadh','Rogassa','Ain El Orak','Arbaouat','El Bnoud','Boualem','Sidi Tifour','Stitten','Brezina','Ghassoul','Krakda','El Abiodh Sidi Cheikh','Chellala','Oulad Bou Ali','Kraakda','Cheguig','Sidi Slimane'],
            'Illizi' => ['Illizi','Djanet','In Amenas','Bordj Omar Driss'],
            'Bordj Bou Arréridj' => ['Bordj Bou Arréridj','Ain Taghrout','Ras El Oued','Bir Kasdali','El Hamadia','Ouled Sidi Brahim','El Achir','Teniet En Nasr','Djaafra','Tixter','Bendouga','El Hassane','Ain Tesra','El Main','Mansoura','Bir Kasdali','Hasnaoua','Colla','Taglait','Ghilassa','Ouled Brahem','Belimour','Medjana','Ain Taghrout','Khelil','Rabta','Oued El Bared','Tesfa'],
            'Boumerdès' => ['Boumerdès','Boudouaou','Khemis El Khechna','Bou Teldja','Tidjelabine','Chabet El Ameur','Thenia','Timezrit','Si Mustapha','Naciria','Djinet','Isser','Zemmouri','Ain Taya','Bordj Menaiel','Ouled Aïssa','Sidi Daoud','Taourga','Larbatache','Hammedi','Baghlia','Sidi Naamane','Ouled Moussa','Benchouia','El Kharrouba','Afir','Ammal'],
            'El Tarf' => ['El Tarf','Ben M\'Hidi','Drean','El Kala','Besbes','Bouteldja','Ain El Assel','Lac des Oiseaux','El Aioun','Chihani','Oum Teboul','Bougous','Raml Souk','Zerizer','Souarekh','Ain Kerma','El Tarf'],
            'Tindouf' => ['Tindouf','Oum El Assel'],
            'Tissemsilt' => ['Tissemsilt','Ain Oulmene','Lardjem','Khemisti','Bordj El Emir Abdelkader','Beni Chaib','El Achir','Ouled Bessem','Theniet El Had','Sidi Lantri','Lazharia','Sidi Boutouchent','Boucaid','Ammari','Sidi Slimane','Beni Lahcen','Layoune','Melaab'],
            'El Oued' => ['El Oued','Robbah','Oued El Alenda','Bayadha','Nakhla','Guemar','Kouinine','Reguiba','Hamraia','Taghzout','Debila','Hassani Abdelkrim','Hadjira','Still','Trifaoui','Magrane','Beni Guecha','Ourmas','Douar El Ma'],
            'Khenchela' => ['Khenchela','Baghaï','El Hamma','Kais','Chechar','Ensigha','El Oueldja','Tamza','Remila','Djellal','Taouzient','Bouhmama','Ain Touila','Metoussa'],
            'Souk Ahras' => ['Souk Ahras','Sedrata','Heddada','Taoura','Ain Zana','Ain Soltane','Oum El Adhaim','Bir Bouhouche','Mechroha','Ouled Driss','Ouillen','Zaarouria','Terreguelt','Drea','Ain Abessa','Khedara','Mdaourouch','Hanancha','Khemissa','Ain Zitoun','Ragouba'],
            'Tipaza' => ['Tipaza','Menaceur','Larhat','Douaouda','Bourkika','Khemisti','Aghabal','Hadjout','Sidi Amar','Bou Ismail','Ahmar El Ain','Bouharoun','Cherchell','Damous','Gouraya','Nador','Sidi Ghiles','Messelmoun','Ain Tagourait','Beni Milleuk','Kolea','Fouka','Chaiba','Ain Benian'],
            'Mila' => ['Mila','Ferdjioua','Chelghoum El Aid','Ain Mellouk','El Mechira','Oued Seguen','Benyahia Abderrahmane','Telerghma','Oued Endja','Grarem Gouga','Tadjenanet','Ain Tine','Sidi Merouane','Ain Beida Harriche','Hamala','Rouached','Zeghaia','Ain Befroum','Bouhatem','Yahia Beni Guecha','Oued Athmania','El Kherba','Elayadi Barbes'],
            'Aïn Defla' => ['Aïn Defla','Djendel','El Attaf','Ain Lechiakh','Bourached','Bordj Emir Khaled','Ain Torki','Ben Allal','Ain Ennasour','Tarik Ibn Ziad','Ain Soltane','Khemis Miliana','Ain Bouyahia','Hammam Righa','Oued Chorfa','Bir Ould Khelifa','El Hassania','Tacheta Zougagha','El Mhaya','Rouina','Arib','Mekhatria','Oued El Djemaa','Boumedfaa','Bathia','Ain Lechiakh'],
            'Naâma' => ['Naâma','Ain Sefra','Tiout','Sfissifa','Moghrar','Assela','Djenane Bourezg','El Biod','Mecheria','Ain Ben Khellil','Makmen Ben Amar','Kasdir','El Gaadel'],
            'Aïn Témouchent' => ['Aïn Témouchent','El Malah','Hammam Bou Hadjar','Ain Kihal','Beni Saf','Oulhaça El Gheraba','El Amria','Ain El Arbaa','Sidi Ben Adda','El Emir Abdelkader','Ain Tolba','Hassi El Ghella','Sidi Boumediene','Ouled Kihal','Aghlal','Terga','Ain Larbaa','Aoubellil','Bouzedjar','Oued Berkeche','Tamzoura'],
            'Ghardaïa' => ['Ghardaïa','Noumerate','El Atteuf','Bounoura','Daya Ben Dahoua','Guerrara','Berriane','Metlili','El Guerrara','Hassi El Fehal','Mansoura','Dhaya','Sebseb','Zelfana','El Menia'],
            'Relizane' => ['Relizane','Ramka','Ain Tarek','Hamri','Sidi M\'hamed Ben Ali','El Hassi','Djidiouia','Oued Rhiou','Sidi Khettab','Sidi M\'hamed Benaouda','El Matmar','Mazouna','Yellel','Ain El Hamam','Lahlef','Ouarizane','Ouled Sidi Mihoub','Mendes','Sidi Lazreug','Zemmoura','Beni Zentis','Ain Rahma'],
            'Timimoun' => ['Timimoun','Ouled Said','Charouine','Aougrout','Talmine','Deldoul','Metarfa','Fenoughil','Ksar Kaddour','Tsabit'],
            'Bordj Badji Mokhtar' => ['Bordj Badji Mokhtar','Timiaouine'],
            'Ouled Djellal' => ['Ouled Djellal','Sidi Khaled','Ras El Miad','Doucen','El Feidh'],
            'Béni Abbès' => ['Béni Abbès','Igli','Timoudi','Erg Ferradj','Tabelbala','Ksabi'],
            'In Salah' => ['In Salah','Foggaret Ezzaouia','In Ghar','Aoulef','Timokten','Tit'],
            'In Guezzam' => ['In Guezzam','Tin Zaouatine'],
            'Touggourt' => ['Touggourt','Temacine','El Hadjira','Taibet','Nezla','Tebesbest','Balidat Ameur','Megarine'],
            'Djanet' => ['Djanet','Bordj Omar Driss'],
            "El M'Ghair" => ["El M'Ghair",'Djamaa','Sidi Khellil','Still','Oum Tiour','Merara','Tendla'],
            'El Meniaa' => ['El Meniaa','Hassi Gara','Berezga','In Tarek'],
        ];

        foreach ($communes as $wilayaNom => $communeList) {
            $wilaya = Wilaya::where('nom', $wilayaNom)->first();
            if (!$wilaya) continue;

            $data = [];
            foreach ($communeList as $commune) {
                $data[] = [
                    'nom'        => $commune,
                    'wilaya_id'  => $wilaya->id,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
            Commune::insert($data);
        }
    }
}